[package]
name = "napi-deno"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_core = "0.114.0"
libloading = "0.7"
napi_sym = { path = "./proc_macro", version = "0.0.0" }
tokio = { version = "1.10.1", features = ["full"] }

